# Generated by Django 2.2.1 on 2019-05-18 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190518_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=datetime.date(2019, 5, 18)),
        ),
    ]
