# Generated by Django 2.2.1 on 2019-06-11 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190518_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=datetime.date(2019, 6, 11)),
        ),
    ]
